(() => {
  const s=document.createElement('script');
  s.src='v2.js?v=3';
  s.defer=true;
  document.head.appendChild(s);
  const spanishCountries=new Set(['AR','BO','CL','CO','CR','CU','DO','EC','SV','GQ','GT','HN','MX','NI','PA','PY','PE','PR','ES','UY','VE']);
  const locale=(navigator.languages&&navigator.languages[0])||navigator.language||'en';
  const region=(locale.match(/[-_]([A-Z]{2})$/i)||[])[1]?.toUpperCase();
  let lang=localStorage.getItem('imprompttu-lang')||(locale.toLowerCase().startsWith('es')||spanishCountries.has(region)?'es':'en');
  let type='Image';
  const es={nav:['Plataforma','Estudio','Consultoría','Precios'],cta:'Empieza a crear',kicker:'Creative Intelligence Platform + Studio',title:'TU IDEA.<br><span class="accent">LA INTELIGENCIA CORRECTA.</span><br>EN UN SOLO LUGAR.',copy:'Crea imágenes, video, audio, ideas y campañas desde una sola plataforma. Cuando necesitas más craft, nuestro Studio entra exactamente donde tú lo dejaste.',create:'Crear ahora',human:'Bring in a human',status:'Intelligent routing activo',label:'¿Qué quieres crear hoy?',placeholder:'Un spot cinematográfico de 15 segundos para una nueva marca de café...',types:['Imagen','Video','Audio','Copy','Campaña'],platform:'PLATAFORMA',platformTitle:'UN PROMPT.<br>LA INTELIGENCIA<br><span class="accent">CORRECTA.</span>',platformCopy:'IMPROMPTTU no te obliga a escoger entre veinte modelos. Entiende qué quieres lograr y enruta cada tarea hacia la mejor combinación de inteligencia, calidad, velocidad y costo.',steps:['Describe la idea','Enrutamos la tarea','Recibes el resultado'],studio:'STUDIO',studioEyebrow:'CUANDO BUENO NO ES SUFICIENTE',studioTitle:'LA IA TE LLEVA LEJOS.<br><span>EL CRAFT TE LLEVA MÁS ALLÁ.</span>',studioCopy:'Dirección creativa, diseño, cinematografía, producción, VFX/SFX, edición y copywriting. El Studio entra al proyecto con todo el contexto, las referencias y el historial creativo intactos.',ways:'TRES FORMAS DE TRABAJAR',pricing:'PRECIOS',priceTitle:'UNA TARIFA PLANA.<br><span class="accent">POTENCIA CREATIVA REAL.</span>',final:'LA INTELIGENCIA<br>NO ES ARTIFICIAL.<br><span>LAS POSIBILIDADES SÍ.</span>',finalCta:'¿Qué vas a crear?'};
  const en={nav:['Platform','Studio','Consulting','Pricing'],cta:'Start creating',kicker:'Creative Intelligence Platform + Studio',title:'YOUR IDEA.<br><span class="accent">THE RIGHT INTELLIGENCE.</span><br>ONE PLACE.',copy:'Create images, video, audio, ideas and campaigns from one platform. When you need more craft, our Studio steps in exactly where you left off.',create:'Create now',human:'Bring in a human',status:'Intelligent routing active',label:'What do you want to create today?',placeholder:'A 15-second cinematic spot for a new coffee brand...',types:['Image','Video','Audio','Copy','Campaign'],platform:'PLATFORM',platformTitle:'ONE PROMPT.<br>THE RIGHT<br><span class="accent">INTELLIGENCE.</span>',platformCopy:'IMPROMPTTU doesn’t make you choose between twenty models. It understands what you want to achieve and routes each task to the best combination of intelligence, quality, speed and cost.',steps:['Describe the idea','We route the task','You get the output'],studio:'STUDIO',studioEyebrow:"WHEN GOOD ISN'T GOOD ENOUGH",studioTitle:'AI GETS YOU THERE.<br><span>CRAFT TAKES YOU FURTHER.</span>',studioCopy:'Creative direction, design, cinematography, production, VFX/SFX, editing and copywriting. The Studio enters the project with all context, references and creative history intact.',ways:'THREE WAYS TO WORK',pricing:'PRICING',priceTitle:'ONE FLAT FEE.<br><span class="accent">SERIOUS CREATIVE POWER.</span>',final:"THE INTELLIGENCE<br>ISN'T ARTIFICIAL.<br><span>THE POSSIBILITIES ARE.</span>",finalCta:'What will you create?'};
  const routes={es:{Image:['Ruta visual','Image · Adaptive','Optimizado para composición, fidelidad e iteración rápida.'],Video:['Ruta de video cinematográfico','Draft → Premium','Boceto eficiente primero; render premium después de aprobar.'],Audio:['Ruta de audio','Voice + Sound','Voz, música o SFX según el prompt.'],Copy:['Ruta de lenguaje creativo','Strategy + Copy','Tono de marca, originalidad y conversión.'],Campaign:['Ruta de campaña','Strategy → Craft','Concepto, copy, visual y producción desde una idea.']},en:{Image:['Visual generation route','Image · Adaptive','Optimized for composition, fidelity and fast iteration.'],Video:['Cinematic video route','Draft → Premium','A low-cost draft first, premium render after approval.'],Audio:['Audio creation route','Voice + Sound','Routes voice, music or SFX according to the prompt.'],Copy:['Creative language route','Strategy + Copy','Balances brand tone, originality and conversion.'],Campaign:['Campaign route','Strategy → Craft','Concept, copy, visual and production from one idea.']}};
  const $=(q)=>document.querySelector(q), $$=(q)=>[...document.querySelectorAll(q)];
  const form=$('#promptForm'),input=$('#promptInput'),chips=$$('.chip'),routeModel=$('#routeModel'),routeMode=$('#routeMode'),routeWhy=$('#routeWhy');
  function cleanCtas(){
    $$('.pill,.text-link,.giant-prompt,.way-grid a').forEach(el=>{
      const walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);
      let node;
      while(node=walker.nextNode()) node.nodeValue=node.nodeValue.replace(/[↗→>]/g,'').replace(/\s{2,}/g,' ');
      el.querySelectorAll('span,b').forEach(n=>{if(!n.textContent.trim())n.remove()});
    });
    const submit=$('.prompt-field button');
    if(submit) submit.textContent=lang==='es'?'Crear':'Create';
  }
  function route(){const r=routes[lang][type];if(routeModel){routeModel.textContent=r[0];routeMode.textContent=r[1];routeWhy.textContent=r[2];}}
  function apply(next,persist=false){lang=next==='en'?'en':'es';const t=lang==='es'?es:en;document.documentElement.lang=lang;const nav=$$('.nav-links a');nav.forEach((a,i)=>a.textContent=t.nav[i]);const topCta=$('.nav>.pill span:first-child');if(topCta)topCta.textContent=t.cta;const kicker=$('.hero-kicker span:last-child');if(kicker)kicker.textContent=t.kicker;const h=$('.hero h1');if(h)h.innerHTML=t.title;const copy=$('.hero-copy');if(copy)copy.textContent=t.copy;const acts=$$('.hero-actions a');if(acts[0])acts[0].querySelector('span').textContent=t.create;if(acts[1])acts[1].querySelector('span').textContent=t.human;const status=$('.status span');if(status)status.textContent=t.status;const lab=$('.prompt-form label');if(lab)lab.textContent=t.label;if(input)input.placeholder=t.placeholder;chips.forEach((c,i)=>c.textContent=t.types[i]);const pLabel=$('#platform .section-index span');if(pLabel)pLabel.textContent=t.platform;const pTitle=$('#platform h2');if(pTitle)pTitle.innerHTML=t.platformTitle;const pCopy=$('.manifesto-copy>p');if(pCopy)pCopy.textContent=t.platformCopy;$$('.mini-stats span').forEach((x,i)=>x.textContent=t.steps[i]);const sLabel=$('#studio .section-index span');if(sLabel)sLabel.textContent=t.studio;const eye=$('.human-copy .eyebrow');if(eye)eye.textContent=t.studioEyebrow;const st=$('.human-copy h2');if(st)st.innerHTML=t.studioTitle;const sc=$('.human-copy>p');if(sc)sc.textContent=t.studioCopy;const wl=$('#consulting .section-index span');if(wl)wl.textContent=t.ways;const pl=$('#pricing .section-index span');if(pl)pl.textContent=t.pricing;const pt=$('.pricing-head h2');if(pt)pt.innerHTML=t.priceTitle;const ft=$('.final-cta h2');if(ft)ft.innerHTML=t.final;const fc=$('.giant-prompt span');if(fc)fc.textContent=t.finalCta;$$('.lang-btn').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));$$('.price-card h3 small').forEach(x=>x.textContent=lang==='es'?'/mes':'/mo');document.title=lang==='es'?'IMPROMPTTU — Inteligencia Creativa':'IMPROMPTTU — Creative Intelligence';route();cleanCtas();if(persist)localStorage.setItem('imprompttu-lang',lang)}
  $$('.lang-btn').forEach(b=>b.addEventListener('click',()=>apply(b.dataset.lang,true)));
  chips.forEach(c=>c.addEventListener('click',()=>{chips.forEach(x=>x.classList.remove('active'));c.classList.add('active');type=c.dataset.type;route()}));
  if(form)form.addEventListener('submit',e=>{e.preventDefault();const text=input.value.trim();if(!text){input.focus();return}const r=routes[lang][type];routeModel.textContent=(lang==='es'?'Enrutando ':'Routing ')+'“'+(text.length>44?text.slice(0,44)+'…':text)+'”';routeMode.textContent=r[1];routeWhy.textContent=lang==='es'?'Prototype mode — el router seleccionará dinámicamente por calidad, velocidad y costo.':'Prototype mode — the router will select dynamically by quality, speed and cost.'});
  apply(lang);setTimeout(cleanCtas,200);
})();