(() => {
  const css = `
  .creative-proof,.brand-brain{padding:110px 0;border-top:1px solid var(--line)}
  .proof-head,.brain-head{display:grid;grid-template-columns:1.15fr .85fr;gap:60px;align-items:end;margin:28px 0 48px}
  .proof-head h2,.brain-head h2{font-family:Manrope,Inter,sans-serif;font-size:clamp(52px,6.8vw,105px);font-weight:500;letter-spacing:-.055em;line-height:.9;margin:0}
  .proof-head p,.brain-head p{max-width:560px;color:#aaa;font-size:17px;margin:0}
  .proof-grid{display:grid;grid-template-columns:1.35fr .65fr;grid-template-rows:340px 340px;gap:12px}.proof-card{position:relative;overflow:hidden;border-radius:20px;border:1px solid #292929;background:#111;isolation:isolate}.proof-card:first-child{grid-row:1/3}.proof-card img{width:100%;height:100%;object-fit:cover;display:block;filter:saturate(.92) contrast(1.06);transition:transform .8s cubic-bezier(.2,.7,.2,1)}.proof-card:hover img{transform:scale(1.035)}.proof-card:after{content:"";position:absolute;inset:0;background:linear-gradient(180deg,transparent 35%,rgba(0,0,0,.78));z-index:1}.proof-meta{position:absolute;z-index:2;left:24px;right:24px;bottom:22px;display:flex;justify-content:space-between;gap:20px;align-items:end}.proof-meta span{font-size:10px;letter-spacing:.14em;text-transform:uppercase;color:#ddd}.proof-meta h3{font-family:Manrope;margin:5px 0 0;font-size:clamp(26px,3vw,48px);letter-spacing:-.04em;line-height:.95}.proof-meta b{font-size:11px;font-weight:500;border:1px solid rgba(255,255,255,.5);padding:8px 10px;border-radius:99px;white-space:nowrap}.proof-note{margin-top:14px;color:#686868;font-size:10px;letter-spacing:.08em;text-transform:uppercase}
  .brain-shell{border:1px solid #2d2d2d;border-radius:26px;overflow:hidden;background:linear-gradient(135deg,#0b0b0b 48%,#24100a 100%)}
  .brain-ui{display:grid;grid-template-columns:.82fr 1.18fr;min-height:620px}.brain-sidebar{padding:28px;border-right:1px solid #303030;display:flex;flex-direction:column}.brain-brand{display:flex;align-items:center;gap:12px;padding-bottom:24px;border-bottom:1px solid #303030}.brain-mark{width:42px;height:42px;border-radius:11px;background:var(--orange);display:grid;place-items:center;color:white;font:600 16px Manrope}.brain-brand b{font:500 15px Manrope}.brain-brand small{display:block;color:#777;margin-top:3px}.brain-nav{display:grid;gap:7px;margin-top:24px}.brain-nav div{padding:12px 13px;border-radius:10px;font-size:12px;color:#777;display:flex;justify-content:space-between}.brain-nav div.active{background:#181818;color:white}.brain-nav i{font-style:normal;color:#4ed184}.brain-score{margin-top:auto;border-top:1px solid #303030;padding-top:22px}.brain-score small{font-size:9px;letter-spacing:.14em;color:#777}.score-row{display:flex;align-items:end;justify-content:space-between;margin-top:8px}.score-row b{font:500 42px Manrope;letter-spacing:-.06em}.score-row span{font-size:11px;color:#4ed184}.brain-main{padding:34px}.brain-main-top{display:flex;justify-content:space-between;gap:20px;align-items:start}.brain-main-top span{font-size:10px;letter-spacing:.14em;color:#888}.brain-main h3{font:500 clamp(34px,4vw,62px)/.95 Manrope;letter-spacing:-.05em;margin:14px 0 8px}.brain-main>p{color:#999;max-width:640px;font-size:14px}.asset-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin-top:34px}.asset{min-height:130px;border:1px solid #333;border-radius:14px;padding:16px;background:rgba(8,8,8,.55);display:flex;flex-direction:column;justify-content:space-between}.asset small{color:#777;font-size:9px;letter-spacing:.12em}.asset b{font:500 15px Manrope}.asset span{font-size:11px;color:#999}.asset .ok{color:#4ed184}.brand-flow{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:10px}.flow-card{padding:22px;border:1px solid #2c2c2c;border-radius:15px;background:#0c0c0c;min-height:190px}.flow-card:nth-child(2){background:#f1eee8;color:#111}.flow-card:nth-child(3){background:linear-gradient(150deg,#431007,#ff4d00);color:white}.flow-card em{font-style:normal;font-size:9px;letter-spacing:.14em}.flow-card h4{font:500 27px/1 Manrope;margin:46px 0 9px;letter-spacing:-.04em}.flow-card p{font-size:12px;margin:0;color:#888}.flow-card:nth-child(2) p{color:#555}.flow-card:nth-child(3) p{color:#ffe3d6}
  .os-line{display:flex;justify-content:space-between;gap:30px;align-items:center;margin-top:34px;padding-top:20px;border-top:1px solid #292929}.os-line b{font:500 clamp(20px,2.5vw,34px) Manrope;letter-spacing:-.04em}.os-line span{font-size:11px;color:#777;text-transform:uppercase;letter-spacing:.12em}
  .portrait-art{background-image:linear-gradient(90deg,rgba(0,0,0,.12),rgba(0,0,0,.05)),url('https://unsplash.com/photos/Vrgdmfy-Tos/download?force=true&w=1400')!important;background-size:cover!important;background-position:center!important}.portrait-core,.portrait-glow{display:none!important}.image-card{background-image:linear-gradient(180deg,rgba(0,0,0,.05),rgba(0,0,0,.7)),url('https://unsplash.com/photos/TxiE5gN9N9s/download?force=true&w=900')!important;background-size:cover!important;background-position:center!important}.image-card .orb{display:none}.nav{backdrop-filter:blur(14px);background:rgba(7,7,7,.72);position:sticky;top:0}
  @media(max-width:900px){.proof-head,.brain-head{grid-template-columns:1fr}.proof-grid{grid-template-columns:1fr;grid-template-rows:520px 330px 330px}.proof-card:first-child{grid-row:auto}.creative-proof,.brand-brain{padding:80px 0}.brain-ui{grid-template-columns:1fr}.brain-sidebar{border-right:0;border-bottom:1px solid #303030;min-height:420px}.asset-grid,.brand-flow{grid-template-columns:1fr 1fr}.brand-flow .flow-card:last-child{grid-column:1/3}}
  @media(max-width:560px){.proof-grid{grid-template-rows:430px 280px 280px}.proof-meta{left:16px;right:16px;bottom:16px}.proof-meta b{display:none}.asset-grid,.brand-flow{grid-template-columns:1fr}.brand-flow .flow-card:last-child{grid-column:auto}.brain-main{padding:22px}.os-line{align-items:start;flex-direction:column}}
  `;
  const style=document.createElement('style'); style.textContent=css; document.head.appendChild(style);

  const section=document.createElement('section'); section.className='creative-proof shell'; section.id='work'; section.innerHTML=`<div class="section-index">[02.5] <span class="proof-label">EXPLORACIONES CREATIVAS</span></div><div class="proof-head"><h2 class="proof-title">NO MOSTRAMOS<br>MODELOS.<br><span class="accent">MOSTRAMOS IDEAS.</span></h2><p class="proof-copy">La tecnología desaparece detrás del resultado. De una dirección visual a una pieza terminada, IMPROMPTTU conecta generación, criterio y craft en un mismo flujo.</p></div><div class="proof-grid"><article class="proof-card"><img loading="lazy" src="https://unsplash.com/photos/Vrgdmfy-Tos/download?force=true&w=1400" alt="Exploración visual editorial"><div class="proof-meta"><div><span>FASHION / MOTION / IMAGE</span><h3>MOVE DIFFERENT.</h3></div><b>CREATIVE STUDY 01</b></div></article><article class="proof-card"><img loading="lazy" src="https://unsplash.com/photos/TxiE5gN9N9s/download?force=true&w=1000" alt="Exploración visual de campaña"><div class="proof-meta"><div><span>CAMPAIGN / ART DIRECTION</span><h3>BE SEEN.</h3></div><b>STUDY 02</b></div></article><article class="proof-card"><img loading="lazy" src="https://unsplash.com/photos/1pbJGBBxc94/download?force=true&w=1000" alt="Exploración editorial de marca"><div class="proof-meta"><div><span>BRAND / EDITORIAL</span><h3>HUMAN, AMPLIFIED.</h3></div><b>STUDY 03</b></div></article></div><div class="proof-note">Exploraciones creativas — referencias visuales mostradas como demostración conceptual, no como trabajo para clientes.</div>`;

  const brain=document.createElement('section'); brain.className='brand-brain shell'; brain.id='brand-brain'; brain.innerHTML=`
    <div class="section-index">[03] <span>BRAND BRAIN</span></div>
    <div class="brain-head"><h2 class="brain-title">TU MARCA NO EMPIEZA<br>DE CERO CON<br><span class="accent">CADA PROMPT.</span></h2><p class="brain-copy">Carga una marca existente o constrúyela desde IMPROMPTTU. Brand Brain convierte sus reglas, assets y decisiones en contexto creativo persistente para todo lo que creas después.</p></div>
    <div class="brain-shell"><div class="brain-ui">
      <aside class="brain-sidebar"><div class="brain-brand"><div class="brain-mark">A</div><div><b>ACME / BRAND BRAIN</b><small class="brain-ready">Contexto activo</small></div></div><div class="brain-nav"><div class="active"><span>Brand Core</span><i>●</i></div><div><span>Guidelines</span><i>●</i></div><div><span>Visual Identity</span><i>●</i></div><div><span>Tone of Voice</span><i>●</i></div><div><span>Asset Library</span><i>●</i></div><div><span>Do’s / Don’ts</span><i>●</i></div><div><span>Campaign Memory</span><i>●</i></div></div><div class="brain-score"><small>BRAND READINESS</small><div class="score-row"><b>94%</b><span class="brain-consistency">ALTA COHERENCIA</span></div></div></aside>
      <div class="brain-main"><div class="brain-main-top"><span>BRAND CONTROL CENTER</span><span>SYNCED ●</span></div><h3 class="brain-ui-title">Una marca.<br>Un contexto.<br>Infinitas ejecuciones.</h3><p class="brain-ui-copy">Cada prompt hereda lo que tu marca ya sabe: cómo habla, cómo se ve, qué evita y qué quiere llegar a ser.</p><div class="asset-grid"><div class="asset"><small>GUIDELINES</small><b class="asset-guidelines">Brand Book.pdf</b><span class="ok">✓ 48 reglas activas</span></div><div class="asset"><small>VISUAL SYSTEM</small><b>Logos / Color / Type</b><span class="ok">✓ Sincronizado</span></div><div class="asset"><small>VOICE</small><b class="asset-voice">Tono + vocabulario</b><span class="ok">✓ Aplicado al copy</span></div><div class="asset"><small>MEMORY</small><b class="asset-memory">Campañas + aprobaciones</b><span class="ok">✓ Aprendizaje continuo</span></div></div></div>
    </div></div>
    <div class="brand-flow"><article class="flow-card"><em>01 / LOAD</em><h4 class="flow1-title">CÁRGALA.</h4><p class="flow1-copy">Sube guidelines, logos, tipografías, referencias, campañas y assets existentes.</p></article><article class="flow-card"><em>02 / BUILD</em><h4 class="flow2-title">CONSTRÚYELA.</h4><p class="flow2-copy">¿Empiezas de cero? Define estrategia, personalidad, identidad y sistema de marca dentro de IMPROMPTTU.</p></article><article class="flow-card"><em>03 / EVOLVE</em><h4 class="flow3-title">HAZLA EVOLUCIONAR.</h4><p class="flow3-copy">Cada decisión aprobada nutre Brand Brain y mantiene coherencia a medida que la marca crece.</p></article></div>
    <div class="os-line"><b class="os-title">CREATE genera. BRAND BRAIN gobierna. STUDIO eleva.</b><span class="os-label">YOUR CREATIVE OPERATING SYSTEM</span></div>
  `;
  const platform=document.querySelector('#platform'); if(platform){platform.insertAdjacentElement('afterend',section);section.insertAdjacentElement('afterend',brain)}
  const studio=document.querySelector('#studio'); if(studio){const idx=studio.querySelector('.section-index'); if(idx) idx.innerHTML='[04] <span data-i18n="studio.label">ESTUDIO</span>'}

  function localize(){const es=document.documentElement.lang!=='en';
    const q=(s)=>document.querySelector(s);
    q('.proof-label').textContent=es?'EXPLORACIONES CREATIVAS':'CREATIVE EXPLORATIONS';q('.proof-title').innerHTML=es?'NO MOSTRAMOS<br>MODELOS.<br><span class="accent">MOSTRAMOS IDEAS.</span>':'WE DON’T SHOW<br>MODELS.<br><span class="accent">WE SHOW IDEAS.</span>';q('.proof-copy').textContent=es?'La tecnología desaparece detrás del resultado. De una dirección visual a una pieza terminada, IMPROMPTTU conecta generación, criterio y craft en un mismo flujo.':'The technology disappears behind the result. From visual direction to finished piece, IMPROMPTTU connects generation, judgment and craft in one flow.';q('.proof-note').textContent=es?'Exploraciones creativas — referencias visuales mostradas como demostración conceptual, no como trabajo para clientes.':'Creative explorations — visual references shown for concept demonstration, not client work.';
    q('.brain-title').innerHTML=es?'TU MARCA NO EMPIEZA<br>DE CERO CON<br><span class="accent">CADA PROMPT.</span>':'YOUR BRAND DOESN’T START<br>FROM ZERO WITH<br><span class="accent">EVERY PROMPT.</span>';q('.brain-copy').textContent=es?'Carga una marca existente o constrúyela desde IMPROMPTTU. Brand Brain convierte sus reglas, assets y decisiones en contexto creativo persistente para todo lo que creas después.':'Bring an existing brand or build one inside IMPROMPTTU. Brand Brain turns its rules, assets and decisions into persistent creative context for everything you create next.';q('.brain-ready').textContent=es?'Contexto activo':'Context active';q('.brain-consistency').textContent=es?'ALTA COHERENCIA':'HIGH CONSISTENCY';q('.brain-ui-title').innerHTML=es?'Una marca.<br>Un contexto.<br>Infinitas ejecuciones.':'One brand.<br>One context.<br>Infinite executions.';q('.brain-ui-copy').textContent=es?'Cada prompt hereda lo que tu marca ya sabe: cómo habla, cómo se ve, qué evita y qué quiere llegar a ser.':'Every prompt inherits what your brand already knows: how it speaks, how it looks, what it avoids and what it wants to become.';q('.asset-guidelines').textContent=es?'Brand Book.pdf':'Brand Book.pdf';q('.asset-voice').textContent=es?'Tono + vocabulario':'Tone + vocabulary';q('.asset-memory').textContent=es?'Campañas + aprobaciones':'Campaigns + approvals';q('.flow1-title').textContent=es?'CÁRGALA.':'LOAD IT.';q('.flow1-copy').textContent=es?'Sube guidelines, logos, tipografías, referencias, campañas y assets existentes.':'Upload guidelines, logos, typography, references, campaigns and existing assets.';q('.flow2-title').textContent=es?'CONSTRÚYELA.':'BUILD IT.';q('.flow2-copy').textContent=es?'¿Empiezas de cero? Define estrategia, personalidad, identidad y sistema de marca dentro de IMPROMPTTU.':'Starting from zero? Define strategy, personality, identity and your brand system inside IMPROMPTTU.';q('.flow3-title').textContent=es?'HAZLA EVOLUCIONAR.':'EVOLVE IT.';q('.flow3-copy').textContent=es?'Cada decisión aprobada nutre Brand Brain y mantiene coherencia a medida que la marca crece.':'Every approved decision feeds Brand Brain and maintains consistency as the brand grows.';q('.os-title').textContent=es?'CREATE genera. BRAND BRAIN gobierna. STUDIO eleva.':'CREATE generates. BRAND BRAIN governs. STUDIO elevates.';}
  localize();document.querySelectorAll('.lang-btn').forEach(b=>b.addEventListener('click',()=>setTimeout(localize,0)));
})();